### ISSUE TITLE
PRE-tag / minted error: Missing Pygments output

### ISSUE THREAD

**Issue by rg-ac** [vvmruder/redmine_doc_pu#6]
When creating a simple wiki page with just a one line pre formatted text (`<pre>just a line</pre>`) the doc_pu run stops with an error:

(/usr/share/texlive/texmf-dist/tex/latex/minted/minted.sty
Package: minted 2015/09/09 v2.1 Yet another Pygments shim for LaTeX
[..]
runsystem(mkdir -p "_minted-template")...executed.
(./_minted-template/default.pygstyle)
[..](./_minted-template/default-pyg-prefix.pygstyle)
[..]
{/var/lib/texmf/fonts/map/pdftex/updmap/pdftex.map}] (./document.tex
\openout3 = `template.pyg'.

runsystem(pygmentize -l  -f latex -P commandprefix=PYG -F tokenmerge -P mathesc
ape=True -o "_minted-template/F161A3B1AC714A7E1A065F1A767BD122B793162BDDAB6C14C
D22D772147BD727.pygtex" "template.pyg" )...executed.

! Package minted Error: Missing Pygments output; \inputminted was
probably given a file that does not exist--otherwise, you may need 
the outputdir package option, or may be using an incompatible build tool.

See the minted package documentation for explanation.
Type  H <return>  for immediate help.
 ...  
 l.8 \end{minted}
This could be caused by using -output-directory or -aux-directory 
without setting minted's outputdir, or by using a build tool that 
changes paths in ways minted cannot detect.

Package hyperref Info: bookmark level for unknown listing defaults to 0 on inpu
t line 9.
)
runsystem(rm "template.pyg")...executed.

The ubuntu package python-pygmentize is installed. Also the texlive package containing the minted 2.1 latex package. Inside the "files" folder I can see the "_minted-template" folder. Looks like permissions are OK. Any ideas why this error happens?

**Comment by vvmruder** [comment]
While using the `<pre>xxx</pre>` notation it is possible to define the language as well. It should look like `<pre><code class="ruby">Place you code here.</code></pre>` for instance. I decided to have highlighted code only. To check which languages are possible please check the minted docs.

You can find the extended wiki textile style guide for redmine here: http://www.redmine.org/projects/redmine/wiki/RedmineTextFormattingTextile
I rely on this for formatting options.

**Comment by vvmruder** [comment]
Please note, that I'am not able (matter of time) to implement each styling out of the box. But the major stuff should work.

**Comment by rg-ac** [comment]
OK, thanks for the info. If I define e. g. ruby it works - no latex errors.
Wishlist:
- Fallback to some kind of plain preformatted if the class is not specified
- Option to disable the horizontal lines
- Option to disable line numbers
- Option to disable / change the pre-subtitle ("Code-Beispiel 1")

**Comment by vvmruder** [comment]
I will see what I can do. ;)

**Comment by vvmruder** [comment]
This issue is ready to be closed? What do you think?

**Comment by rg-ac** [comment]
Yes, thx. Can stay closed.
